// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Teamorgchart
{
    using Models;
    using Newtonsoft.Json;

    /// <summary>
    /// </summary>
    public partial interface ITeamOrgChartWebUIDirectoryApp : System.IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        System.Uri BaseUri { get; set; }

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        JsonSerializerSettings DeserializationSettings { get; }


        /// <summary>
        /// Gets the IChartDataApi.
        /// </summary>
        IChartDataApi ChartDataApi { get; }

        /// <summary>
        /// Gets the IChartsApi.
        /// </summary>
        IChartsApi ChartsApi { get; }

        /// <summary>
        /// Gets the IPositionsApi.
        /// </summary>
        IPositionsApi PositionsApi { get; }

        /// <summary>
        /// Gets the IRemappingsApi.
        /// </summary>
        IRemappingsApi RemappingsApi { get; }

    }
}
