// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Teamorgchart.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class JsonChartItemViewModel
    {
        /// <summary>
        /// Initializes a new instance of the JsonChartItemViewModel class.
        /// </summary>
        public JsonChartItemViewModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the JsonChartItemViewModel class.
        /// </summary>
        public JsonChartItemViewModel(int? id = default(int?), string orgChartDefinitionId = default(string), string uniqueId = default(string), string managerId = default(string), string jsonData = default(string))
        {
            Id = id;
            OrgChartDefinitionId = orgChartDefinitionId;
            UniqueId = uniqueId;
            ManagerId = managerId;
            JsonData = jsonData;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OrgChartDefinitionId")]
        public string OrgChartDefinitionId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UniqueId")]
        public string UniqueId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ManagerId")]
        public string ManagerId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "JsonData")]
        public string JsonData { get; set; }

    }
}
