// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Teamorgchart.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Remapping
    {
        /// <summary>
        /// Initializes a new instance of the Remapping class.
        /// </summary>
        public Remapping()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Remapping class.
        /// </summary>
        public Remapping(int? id = default(int?), string uniqueId = default(string), string friendlyUniqueId = default(string), string managerId = default(string), string friendlyManagerId = default(string), string mappedId = default(string), string friendlyMappedId = default(string))
        {
            Id = id;
            UniqueId = uniqueId;
            FriendlyUniqueId = friendlyUniqueId;
            ManagerId = managerId;
            FriendlyManagerId = friendlyManagerId;
            MappedId = mappedId;
            FriendlyMappedId = friendlyMappedId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UniqueId")]
        public string UniqueId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FriendlyUniqueId")]
        public string FriendlyUniqueId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ManagerId")]
        public string ManagerId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FriendlyManagerId")]
        public string FriendlyManagerId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MappedId")]
        public string MappedId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FriendlyMappedId")]
        public string FriendlyMappedId { get; set; }

    }
}
